--- 
title: "lineaRmodels"
author: "Léo Belzile"
date: "version of `r Sys.Date()`"
site: bookdown::bookdown_site
output:
  bookdown::gitbook:
    highlight: tango
  bookdown::pdf_book:
    includes:
      in_header: preamble.tex
documentclass: book
header-includes:
  - \usepackage{amsmath,amssymb,mathtools}
bibliography: [book.bib, packages.bib]
biblio-style: apalike2
link-citations: yes
github-repo: lbelzile/lineaRmodels
always_allow_html: yes
description: "This is a web complement to MATH 341 (Linear Models), a first regression course for EPFL mathematicians."
---


# Preliminary remarks {-}

This is a web complement to MATH 341 (Linear Models), a first regression course for EPFL mathematicians.


We shall use the **R** programming language througout the course (as it is free and it is used in other statistics courses at EPFL). Visit [the R-project website](https://cran.r-project.org/) to download the program. The most popular graphical cross-platform front-end is [RStudio Desktop](https://www.rstudio.com/products/rstudio/download/).

**R** is an object-oriented interpreted language. It differs from usual programming languages in that it is designed for interactive analyses. 


Since **R** is not a conventional programming language, my teaching approach will be learning-by-doing. The benefit of using *Rmarkdown* is that you see the output directly and you can also copy the code.

\newcommand{\bs}[1]{\boldsymbol{#1}}
\newcommand{\Hmat}{\mathbf{H}}
\newcommand{\Mmat}{\mathbf{M}}
\newcommand{\mX}{\mathbf{X}}
\newcommand{\bX}{{\mathbf{X}}}
\newcommand{\bx}{{\mathbf{x}}}
\newcommand{\by}{{\boldsymbol{y}}}
\newcommand{\bY}{{\boldsymbol{Y}}}
\newcommand{\eps}{\varepsilon}
\newcommand{\beps}{\boldsymbol{\varepsilon}}
\newcommand{\bbeta}{\boldsymbol{\beta}}
\newcommand{\hbb}{\hat{\boldsymbol{\beta}}}
\newcommand{\limni}{\lim_{n \ra \infty}}
\newcommand{\Sp}{\mathscr{S}}
